spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userauthdb?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: 3199ac38f5e85c9a991f34d243886c9d
    password: 80e8a276c0c185e53dd9561bf09343dd
    properties:
      mail:
        from: ctruiz0515@gmail.com
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  paths-to-match: /api/**
  cache:
    disabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
    secret: "TuClaveSecretaMuySeguraYComplejaQueDebeTenerAlMenos32Caracteres123456"
    expiration: 86400
app:
  base-url: http://localhost:8080

server:
  port: 8080
